apiVersion: v1
kind: Pod
metadata:
  name: centos-nginx-pod
  labels:
    app: centos-nginx
spec: 

  volumes:
    - name: my-web-content
      emptyDir: {}

  containers: 
    - name: centos-producer
      image: centos:latest
      command: ["/bin/bash"]
      args: [ "-c" , "while true ; do echo 'test website' > /centos-pod-data/index.html ; sleep 10 ; done" ]
      ports:
        - containerPort: 1234
      volumeMounts:
        - name: my-web-content
          mountPath: /centos-pod-data

    - name: nginx-consumer
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
           - name: my-web-content
             mountPath: /usr/share/nginx/html
